version: '3'
services:
  ministry-svc:
    image: "servantscode/ministry-svc:latest"
    ports:
     - "81:8080"
    external_links:
      - person_svc:postgres

volumes:
  postgres:

networks:
  default:
    external:
      name: docker-elk_elk
