version: '3'
services:
  ministry-svc:
    image: "servantscode/ministry-svc:latest"
    ports:
     - "80:8080"
  postgres:
    image: "postgres"
    ports:
     - "5432:5432"
    volumes:
     - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "SuperSecret"

volumes:
  postgres:

networks:
  default:
    external:
      name: docker-elk_elk
