apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministry-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ministry-svc
  template:
    metadata:
      labels:
        app: ministry-svc
    spec:
      containers:
      - name: ministry-svc
        image: servantscode/ministry-svc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
        env:
        - name: ES_JAVA_OPTS 
          value: "-Xmx128m -Xms128m"
---
kind: Service
apiVersion: v1
metadata:
  name: ministry-svc
spec:
  selector:
    app: ministry-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
